'use client';

import { useEffect, useState } from 'react';
import { Loader2, Download, BarChart3, TrendingUp, Users, AlertTriangle } from 'lucide-react';
import StatCard from '@/components/ui/StatCard';
import { getTodayDate } from '@/lib/utils';
import { useAuth } from '@/lib/auth-context';

export default function ReportsPage() {
  const { user } = useAuth();
  
  // Default to last 7 days
  const defaultEnd = getTodayDate();
  const d = new Date();
  d.setDate(d.getDate() - 7);
  const defaultStart = d.toISOString().split('T')[0];

  const [startDate, setStartDate] = useState(defaultStart);
  const [endDate, setEndDate] = useState(defaultEnd);
  const [loading, setLoading] = useState(false);
  const [reportData, setReportData] = useState<any>(null);

  const fetchReport = async () => {
    setLoading(true);
    try {
      const res = await fetch(`/api/reports?startDate=${startDate}&endDate=${endDate}`);
      if (res.ok) {
        const data = await res.json();
        setReportData(data);
      }
    } catch (error) {
      console.error('Failed to fetch report', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    fetchReport();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handlePrint = () => {
    window.print();
  };

  if (user?.role === 'officer') {
    return (
      <div className="card" style={{ textAlign: 'center', padding: '4rem 2rem' }}>
        <AlertTriangle size={48} style={{ color: 'var(--color-warning)', margin: '0 auto 1rem' }} />
        <h2>Access Restricted</h2>
        <p style={{ color: 'var(--color-text-muted)', marginTop: '0.5rem' }}>
          You do not have permission to view management reports.
        </p>
      </div>
    );
  }

  return (
    <div className="animate-fade-in printable">
      <div className="page-header print-hide">
        <div>
          <h1 className="page-title">Management Reports</h1>
          <p className="page-subtitle">Aggregated data and analytics for security operations.</p>
        </div>
        <div style={{ display: 'flex', gap: '0.75rem' }}>
          <button className="btn btn-primary" onClick={handlePrint}>
            <Download size={16} /> Export PDF / Print
          </button>
        </div>
      </div>

      <div className="print-only" style={{ display: 'none', marginBottom: '2rem' }}>
        <h2>ASR Security Control Room — Operations Report</h2>
        <p>Reporting Period: {startDate} to {endDate}</p>
        <p>Generated By: {user?.name} on {new Date().toLocaleString()}</p>
        <hr style={{ borderColor: '#e2e8f0', margin: '1rem 0' }} />
      </div>

      {/* Filters (Hidden on Print) */}
      <div className="card print-hide" style={{ marginBottom: '1.5rem' }}>
        <div style={{ display: 'flex', alignItems: 'flex-end', gap: '1rem', flexWrap: 'wrap' }}>
          <div className="form-group" style={{ flex: 1, minWidth: '200px', marginBottom: 0 }}>
            <label className="form-label">Start Date</label>
            <input 
              type="date" 
              className="form-input" 
              value={startDate} 
              onChange={(e) => setStartDate(e.target.value)} 
            />
          </div>
          <div className="form-group" style={{ flex: 1, minWidth: '200px', marginBottom: 0 }}>
            <label className="form-label">End Date</label>
            <input 
              type="date" 
              className="form-input" 
              value={endDate} 
              onChange={(e) => setEndDate(e.target.value)} 
            />
          </div>
          <button className="btn btn-secondary" onClick={fetchReport} disabled={loading} style={{ height: '42px' }}>
            {loading ? <Loader2 size={16} className="animate-spin" /> : 'Generate Report'}
          </button>
        </div>
      </div>

      {loading && !reportData ? (
        <div style={{ padding: '4rem', textAlign: 'center' }}>
          <Loader2 size={32} className="animate-spin" style={{ margin: '0 auto 1rem', color: 'var(--color-accent)' }} />
          <p>Compiling report data...</p>
        </div>
      ) : reportData ? (
        <>
          <h2 style={{ fontSize: '1.125rem', marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <TrendingUp size={20} style={{ color: 'var(--color-accent)' }} /> 
            Executive Summary
          </h2>
          
          <div className="grid-stats stagger-children" style={{ marginBottom: '2rem' }}>
            <StatCard label="Total Visitors" value={reportData.summary.visitors} icon={<Users size={20} />} color="#3b82f6" />
            <StatCard label="Total Vehicles" value={reportData.summary.vehicles} icon={<TrendingUp size={20} />} color="#10b981" />
            <StatCard label="Incidents Reported" value={reportData.summary.incidents} icon={<AlertTriangle size={20} />} color="#ef4444" />
            <StatCard label="Goods Received" value={reportData.summary.goods} icon={<BarChart3 size={20} />} color="#f59e0b" />
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem', marginBottom: '2rem' }}>
            {/* Incidents Breakdown */}
            <div className="card">
              <h3 style={{ fontSize: '1rem', marginBottom: '1rem', borderBottom: '1px solid var(--color-border)', paddingBottom: '0.5rem' }}>
                Incident Resolution Status
              </h3>
              {reportData.breakdowns.incidentsByStatus.length > 0 ? (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                  {reportData.breakdowns.incidentsByStatus.map((stat: { _id: string, count: number }) => (
                    <div key={stat._id} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                      <span style={{ textTransform: 'capitalize' }}>{stat._id}</span>
                      <span className="badge badge-secondary">{stat.count}</span>
                    </div>
                  ))}
                </div>
              ) : (
                <p style={{ color: 'var(--color-text-muted)' }}>No incidents recorded in this period.</p>
              )}
            </div>

            {/* Visitors Breakdown */}
            <div className="card">
              <h3 style={{ fontSize: '1rem', marginBottom: '1rem', borderBottom: '1px solid var(--color-border)', paddingBottom: '0.5rem' }}>
                Top Visited Departments
              </h3>
              {reportData.breakdowns.visitorsByDepartment.length > 0 ? (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                  {reportData.breakdowns.visitorsByDepartment
                    .sort((a: { _id: string, count: number }, b: { _id: string, count: number }) => b.count - a.count)
                    .map((stat: { _id: string, count: number }) => (
                    <div key={stat._id} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                      <span>{stat._id}</span>
                      <span className="badge badge-secondary">{stat.count}</span>
                    </div>
                  ))}
                </div>
              ) : (
                <p style={{ color: 'var(--color-text-muted)' }}>No visitors recorded in this period.</p>
              )}
            </div>
          </div>
          
          {/* Print specific styling injected here */}
          <style dangerouslySetInnerHTML={{__html: `
            @media print {
              .print-hide { display: none !important; }
              .print-only { display: block !important; }
              .card { box-shadow: none !important; border: 1px solid #e2e8f0 !important; page-break-inside: avoid; }
              body { background: white !important; color: black !important; }
              * { color: black !important; text-shadow: none !important; }
            }
          `}} />
        </>
      ) : null}
    </div>
  );
}
